
; Drupal version
core = 6.x
api = 2

; Contrib modules
projects[advanced_help][subdir] = contrib
projects[advanced_help][version] = 1.2
projects[cck][subdir] = contrib
projects[cck][version] = 2.9
projects[context][subdir] = contrib
projects[context][version] = 3.0
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.8
projects[debut][subdir] = contrib
projects[debut][version] = 1.0-beta1
projects[debut_image][subdir] = contrib
projects[debut_image][version] = 1.0-beta1
projects[features][subdir] = contrib
projects[features][version] = 1.0
projects[filefield][subdir] = contrib
projects[filefield][version] = 3.9
projects[helpinjector][subdir] = contrib
projects[imageapi][subdir] = contrib
projects[imageapi][version] = 1.9
projects[imagecache][subdir] = contrib
projects[imagecache][version] = 2.0-beta10
projects[imagefield][subdir] = contrib
projects[imagefield][version] = 3.9
projects[pathauto][subdir] = contrib
projects[pathauto][version] = 1.5
projects[strongarm][subdir] = contrib
projects[strongarm][version] = 2.0
projects[token][subdir] = contrib
projects[token][version] = 1.15
projects[views][subdir] = contrib
projects[views][version] = 2.12

