
; Drupal version
core = 6.x
api = 2

; Contrib modules
projects[advanced_help][subdir] = contrib
projects[advanced_help][version] = 1.2
projects[debut][subdir] = contrib
projects[debut][version] = 1.0-beta1
projects[features][subdir] = contrib
projects[features][version] = 1.0
projects[pathauto][subdir] = contrib
projects[pathauto[version] = 1.5
projects[token][subdir] = contrib
projects[token][version] = 1.15
