<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function fill_pdf_ubercart_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'type' => 'product',
  'language' => '',
  'uid' => '1',
  'status' => '1',
  'created' => '1265273424',
  'changed' => '1331855854',
  'comment' => '0',
  'promote' => '1',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '187',
  'title' => 'Plus',
  'body' => '<ul>
<li>1000 PDF merges per month</li>
<li>Fill image fields (see <a href="/content/faq#qi">FAQ</a>)</li>
<li>Priority support on <a href="http://drupal.org/project/issues/fillpdf">module & service issues</a></li>
<li>Email support</li>
</ul>',
  'teaser' => '<ul>
<li>1000 PDF merges per month</li>
<li>Fill image fields (see <a href="/content/faq#qi">FAQ</a>)</li>
<li>Priority support on <a href="http://drupal.org/project/issues/fillpdf">module & service issues</a></li>
<li>Email support</li>
</ul>',
  'log' => '',
  'revision_timestamp' => '1331855854',
  'format' => '1',
  'name' => 'Wizard',
  'picture' => '',
  'data' => 'a:6:{s:8:"new_role";i:0;s:12:"new_role_add";s:1:"5";s:16:"new_role_add_qty";s:0:"";s:24:"new_role_add_granularity";s:3:"day";s:7:"contact";i:0;s:13:"form_build_id";s:37:"form-14d34be97cd48def83958fe8e6151ba7";}',
  'model' => '2',
  'list_price' => '0.00000',
  'cost' => '0.00000',
  'sell_price' => '10.00000',
  'weight' => '0',
  'weight_units' => 'lb',
  'length' => '0',
  'width' => '0',
  'height' => '0',
  'length_units' => 'in',
  'pkg_qty' => '1',
  'default_qty' => '0',
  'unique_hash' => '',
  'ordering' => '0',
  'shippable' => '0',
  'path' => 'content/plus',
  'field_max_pdf_merges' => array(
    '0' => array(
      'value' => '1000',
    ),
  ),
  'last_comment_timestamp' => '1265273424',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'files' => array(),
  'page_title' => FALSE,
  'uuid' => '0308be0f-6edc-11e1-80db-001bfc5286c3',
  'revision_uuid' => 'a2a7d962-6efa-11e1-8a1f-7f9a88d8a5b3',
  'pathauto_perform_alias' => FALSE,
  'date' => '2010-02-04 01:50:24 -0700',
);
  $nodes[] = array(
  'type' => 'product',
  'language' => '',
  'uid' => '1',
  'status' => '1',
  'created' => '1265273818',
  'changed' => '1331855884',
  'comment' => '0',
  'promote' => '1',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '187',
  'title' => 'Premium',
  'body' => '<ul>
<li><strong>2000</strong> PDF merges per month</li>
<li>Fill image fields (see <a href="/content/faq#qi">FAQ</a>)</li>
<li>Priority support on <a href="http://drupal.org/project/issues/fillpdf">module & service issues</a></li>
<li>Email support</li>
<li>Help setting up one initial form (Webform/CCK-to-PDF mapping)*</li>
</ul>',
  'teaser' => '<ul>
<li><strong>2000</strong> PDF merges per month</li>
<li>Fill image fields (see <a href="/content/faq#qi">FAQ</a>)</li>
<li>Priority support on <a href="http://drupal.org/project/issues/fillpdf">module & service issues</a></li>
<li>Email support</li>
<li>Help setting up one initial form (Webform/CCK-to-PDF mapping)*</li>
</ul>',
  'log' => '',
  'revision_timestamp' => '1331855884',
  'format' => '2',
  'name' => 'Wizard',
  'picture' => '',
  'data' => 'a:6:{s:8:"new_role";i:0;s:12:"new_role_add";s:1:"5";s:16:"new_role_add_qty";s:0:"";s:24:"new_role_add_granularity";s:3:"day";s:7:"contact";i:0;s:13:"form_build_id";s:37:"form-14d34be97cd48def83958fe8e6151ba7";}',
  'model' => '3',
  'list_price' => '0.00000',
  'cost' => '0.00000',
  'sell_price' => '20.00000',
  'weight' => '0',
  'weight_units' => 'lb',
  'length' => '0',
  'width' => '0',
  'height' => '0',
  'length_units' => 'in',
  'pkg_qty' => '1',
  'default_qty' => '0',
  'unique_hash' => '',
  'ordering' => '0',
  'shippable' => '0',
  'field_max_pdf_merges' => array(
    '0' => array(
      'value' => '2000',
    ),
  ),
  'last_comment_timestamp' => '1265273818',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'files' => array(),
  'page_title' => FALSE,
  'uuid' => '031051fc-6edc-11e1-80db-001bfc5286c3',
  'revision_uuid' => 'b41be4e0-6efa-11e1-8a1f-7f9a88d8a5b3',
  'date' => '2010-02-04 01:56:58 -0700',
);
  $nodes[] = array(
  'type' => 'product',
  'language' => '',
  'uid' => '187',
  'status' => '1',
  'created' => '1330653515',
  'changed' => '1331855907',
  'comment' => '0',
  'promote' => '1',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '187',
  'title' => 'Business',
  'body' => '<ul>
<li><strong>Unlimited PDF merges each month</strong></li>
<li>Fill image fields (see <a href="/content/faq#qi">FAQ</a>)</li>
<li>Priority support on <a href="http://drupal.org/project/issues/fillpdf">module & service issues</a></li>
<li><strong>Priority</strong> email support</li>
<li>Help setting up one initial form (Webform/CCK-to-PDF mapping)*</li>
</ul>',
  'teaser' => '<ul>
<li><strong>Unlimited PDF merges each month</strong></li>
<li>Fill image fields (see <a href="/content/faq#qi">FAQ</a>)</li>
<li>Priority support on <a href="http://drupal.org/project/issues/fillpdf">module & service issues</a></li>
<li><strong>Priority</strong> email support</li>
<li>Help setting up one initial form (Webform/CCK-to-PDF mapping)*</li>
</ul>',
  'log' => '',
  'revision_timestamp' => '1331855907',
  'format' => '2',
  'name' => 'wizonesolutions',
  'picture' => '',
  'data' => 'a:7:{s:6:"mollom";a:2:{s:10:"session_id";s:29:"1283813741-1009067ea2b9d5e865";s:7:"captcha";s:5:"gbe4m";}s:7:"contact";i:1;s:8:"new_role";i:0;s:12:"new_role_add";s:1:"5";s:16:"new_role_add_qty";s:0:"";s:24:"new_role_add_granularity";s:3:"day";s:13:"form_build_id";s:37:"form-205ff3b82cbdb6c0dd03a84c862bf050";}',
  'model' => '4',
  'list_price' => '0.00000',
  'cost' => '0.00000',
  'sell_price' => '40.00000',
  'weight' => '0',
  'weight_units' => 'lb',
  'length' => '0',
  'width' => '0',
  'height' => '0',
  'length_units' => 'in',
  'pkg_qty' => '1',
  'default_qty' => '0',
  'unique_hash' => '',
  'ordering' => '0',
  'shippable' => '0',
  'field_max_pdf_merges' => array(
    '0' => array(
      'value' => '0',
    ),
  ),
  'last_comment_timestamp' => '1330653515',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'files' => array(),
  'page_title' => FALSE,
  'uuid' => '93f5fab8-6411-11e1-80db-001bfc5286c3',
  'revision_uuid' => 'c1ed3be6-6efa-11e1-8a1f-7f9a88d8a5b3',
  'date' => '2012-03-01 18:58:35 -0700',
);
  $nodes[] = array(
  'type' => 'product',
  'language' => '',
  'uid' => '187',
  'status' => '1',
  'created' => '1330842623',
  'changed' => '1331855845',
  'comment' => '0',
  'promote' => '1',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '187',
  'title' => 'Basic',
  'body' => '<ul>
<li>500 PDF merges each month</li>
<li>Fill image fields (see <a href="/content/faq#qi">FAQ</a>)</li>
<li>Email support</li>
</ul>',
  'teaser' => '<ul>
<li>500 PDF merges each month</li>
<li>Fill image fields (see <a href="/content/faq#qi">FAQ</a>)</li>
<li>Email support</li>
</ul>',
  'log' => '',
  'revision_timestamp' => '1331855845',
  'format' => '2',
  'name' => 'wizonesolutions',
  'picture' => '',
  'data' => 'a:7:{s:6:"mollom";a:2:{s:10:"session_id";s:29:"1283813741-1009067ea2b9d5e865";s:7:"captcha";s:5:"gbe4m";}s:7:"contact";i:1;s:8:"new_role";i:0;s:12:"new_role_add";s:1:"5";s:16:"new_role_add_qty";s:0:"";s:24:"new_role_add_granularity";s:3:"day";s:13:"form_build_id";s:37:"form-205ff3b82cbdb6c0dd03a84c862bf050";}',
  'model' => '5',
  'list_price' => '0.00000',
  'cost' => '0.00000',
  'sell_price' => '5.00000',
  'weight' => '0',
  'weight_units' => 'lb',
  'length' => '0',
  'width' => '0',
  'height' => '0',
  'length_units' => 'in',
  'pkg_qty' => '1',
  'default_qty' => '0',
  'unique_hash' => '',
  'ordering' => '0',
  'shippable' => '0',
  'path' => 'content/basic',
  'field_max_pdf_merges' => array(
    '0' => array(
      'value' => '500',
    ),
  ),
  'last_comment_timestamp' => '1330842623',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'files' => array(),
  'page_title' => FALSE,
  'uuid' => 'e65e3e8b-6eda-11e1-80db-001bfc5286c3',
  'revision_uuid' => '9cd811c8-6efa-11e1-8a1f-7f9a88d8a5b3',
  'pathauto_perform_alias' => FALSE,
  'date' => '2012-03-03 23:30:23 -0700',
);
  return $nodes;
}
